// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj2wsNO9aVKxGqyOKmltNSISJO6HhXwP8',
    appId: '1:704443417963:web:d271a8a35b417daad1382e',
    messagingSenderId: '704443417963',
    projectId: 'reprosync-b8b00',
    authDomain: 'reprosync-b8b00.firebaseapp.com',
    storageBucket: 'reprosync-b8b00.firebasestorage.app',
    measurementId: 'G-EG1B8JFYFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiEPFsEsjSEiZ3PJ7dJSAETvMuU74IIQU',
    appId: '1:704443417963:android:af76847919550be2d1382e',
    messagingSenderId: '704443417963',
    projectId: 'reprosync-b8b00',
    storageBucket: 'reprosync-b8b00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGlktOPdOm6u1_GTzVShFmUjGuaK3LGB4',
    appId: '1:704443417963:ios:689638661494bc1cd1382e',
    messagingSenderId: '704443417963',
    projectId: 'reprosync-b8b00',
    storageBucket: 'reprosync-b8b00.firebasestorage.app',
    iosBundleId: 'com.example.synergy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGlktOPdOm6u1_GTzVShFmUjGuaK3LGB4',
    appId: '1:704443417963:ios:689638661494bc1cd1382e',
    messagingSenderId: '704443417963',
    projectId: 'reprosync-b8b00',
    storageBucket: 'reprosync-b8b00.firebasestorage.app',
    iosBundleId: 'com.example.synergy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj2wsNO9aVKxGqyOKmltNSISJO6HhXwP8',
    appId: '1:704443417963:web:7e413edf580adc2cd1382e',
    messagingSenderId: '704443417963',
    projectId: 'reprosync-b8b00',
    authDomain: 'reprosync-b8b00.firebaseapp.com',
    storageBucket: 'reprosync-b8b00.firebasestorage.app',
    measurementId: 'G-7L4VW4ZEHK',
  );
}
